# Generated by Django 5.1.6 on 2025-03-06 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=10)),
                ('st101', models.CharField(blank=True, max_length=255, null=True)),
                ('st110', models.CharField(blank=True, max_length=255, null=True)),
                ('st111', models.CharField(blank=True, max_length=255, null=True)),
                ('st112', models.CharField(blank=True, max_length=255, null=True)),
                ('st208', models.CharField(blank=True, max_length=255, null=True)),
                ('st406', models.CharField(blank=True, max_length=255, null=True)),
                ('st407', models.CharField(blank=True, max_length=255, null=True)),
                ('st411', models.CharField(blank=True, max_length=255, null=True)),
                ('st412', models.CharField(blank=True, max_length=255, null=True)),
                ('st413', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
