# Generated by Django 5.1.6 on 2025-03-06 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='st101',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='st110',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='st111',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='st112',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='st208',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='st406',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='st407',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='st411',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='st412',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='st413',
        ),
        migrations.AlterField(
            model_name='timetable',
            name='time',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor', models.CharField(max_length=100)),
                ('room', models.CharField(max_length=50)),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=10)),
                ('start_time', models.CharField(max_length=20)),
                ('end_time', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=10)),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.timetable')),
            ],
        ),
    ]
