# Generated by Django 5.1.6 on 2025-03-06 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_timetable_st101_remove_timetable_st110_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'Class Schedule', 'verbose_name_plural': 'Class Schedules'},
        ),
        migrations.AlterModelOptions(
            name='timetable',
            options={'verbose_name': 'Timetable Slot', 'verbose_name_plural': 'Timetable Slots'},
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('timetable', 'room', 'subject', 'section')},
        ),
        migrations.AddField(
            model_name='timetable',
            name='day_group',
            field=models.CharField(blank=True, choices=[('Monday/Wednesday', 'Monday/Wednesday'), ('Tuesday/Thursday', 'Tuesday/Thursday'), ('Friday/Saturday', 'Friday/Saturday')], default='Monday/Wednesday', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='timetable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='myapp.timetable'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='time',
            field=models.TimeField(unique=True),
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='day',
        ),
    ]
